n = str(input('Seu nome completo: ')).strip()
nome = n.split()
print('Muito prazer em te conhecer <3 ')
print('Seu primeiro nome e: {}'.format(nome[0]))
print('Seu ultimo nome e: {}'.format(nome[len(nome)-1]) )